conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),

]

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('privacy/', views.privacy, name='privacy'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('new/', views.new, name='new'),
    path('', views.items, name='items'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

shockstan/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', include('core.urls')),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Username',
        'class': 'w-full py-4 px-6 rounded-xl border'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password',
        'class': 'w-full py-4 px-6 rounded-xl border'
    }))


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Username',
        'class': 'w-full py-4 px-6 rounded-xl border'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'email',
        'class': 'w-full py-4 px-6 rounded-xl border'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password',
        'class': 'w-full py-4 px-6 rounded-xl border'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm Password',
        'class': 'w-full py-4 px-6 rounded-xl border'
    }))

core/views.py
from django.shortcuts import render, redirect
from item.models import Category, Item
from . forms import SignupForm


def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()
    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items,
    })


def contact(request):
    return render(request, 'core/contact.html')


def about(request):
    return render(request, 'core/about.html')


def privacy(request):
    return render(request, 'core/privacy.html')


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:
        form = SignupForm()
    return render(request, 'core/signup.html', {
        'form': form
    })

core/templates/core/about.html
{% extends 'core/base.html' %}
{% block title %}About{% endblock %}
 {% block content %}
<div class="flex justify-center h-screen">
 <h1 class="font-bold text-orange-800">This is created by <strong>Arvindh KM</strong>, who is interested in software development and has various skills needed for it</h1>
</div>
{% endblock %}

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}{% endblock %} | ShockSTAN</title>
</head>
<body><div class="bg-amber-300">
<nav class="py-6 px-6 flex justify-between items-center border-b border-black-200">
    <a href="/" class="text-xl font-semibold">ShockStan Sports</a>

    <div class="space-x-6">
        <a href="{% url 'item:new' %}" class="px-6 py-2 text-lg font-semibold hover:text-orange-500 hover:bg-white rounded-xl">Add Equipment</a>
        <a href="{% url 'item:items' %}" class="px-6 py-2 text-lg font-semibold hover:text-orange-500 hover:bg-white rounded-xl">Browse</a>

        {% if request.user.is_authenticated %}
        <a href="#">Hi, <strong>{{ request.user.username }}</strong></a>
        <a href="{% url 'conversation:inbox' %}" class="px-6 py-2 text-lg font-semibold bg-orange-500 text-white rounded-xl hover:bg-orange-700">Inbox</a>
        <a href="{% url 'dashboard:index' %}" class="px-6 py-2 text-lg font-semibold bg-orange-500 text-white rounded-xl hover:bg-orange-700">Dashboard</a>
        <a href="{% url 'logout' %}" class="px-6 py-2 text-lg font-semibold bg-orange-500 text-white rounded-xl hover:bg-orange-700">Logout</a>
        {% else %}
        <a href="{% url 'core:signup' %}" class="px-6 py-2 text-lg font-semibold bg-orange-500 text-white rounded-xl hover:bg-orange-700">Sign UP</a>
        <a href="{% url 'core:login' %}" class="px-6 py-2 text-lg font-semibold bg-orange-500 text-white rounded-xl hover:bg-orange-700">LOGIN!!</a>
        {% endif %}
    </div>
</nav>
<div class="px-6 py-6">
    {% block content %}
    {% endblock %}
</div>
<footer class="py-6 px-6 flex justify-between bg-black">
    <div class="w-2/3 pr-10">
        <h3 class="mb-5 font-bold text-xl text-white">About</h3>
        <p class="text-base text-lime-300">
        You can get every sport equipment here. <br> You won't regret buying from us!</p>
    </div>
    <div class="w-1/3">
        <h3 class="mb-5 font-bold text-xl text-white">Menu</h3>
        <ul class="space-y-2">
            <li><a href="{% url 'core:about' %}" class="text-sm text-lime-300 hover:text-gray-400">About</a></li>
            <li><a href="{% url 'core:contact' %}" class="text-sm text-lime-300 hover:text-gray-400">Contact</a></li>
            <li><a href="{% url 'core:privacy' %}" class="text-sm text-lime-300 hover:text-gray-400">Privacy Policy</a></li>
        </ul>
    </div>
</footer>
</div>
</body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}
{% block title %}Contact{% endblock %}
 {% block content %}
<div class="h-screen">
{% if request.user.is_authenticated %}
<p class="text-xl font-semibold text-center text-red-600">Mail the owner at <strong>{{ request.user.email }}</strong></p>
{% else %}
<p>Check the domain: <strong>shockstan.com</strong></p>
{% endif %}
</div>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}
{% block title %}Welcome{% endblock %}
 {% block content %}

<div class="mt-6 px-6 py-6 bg-amber-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center font-bold text-orange-600">New Additions</h2>
    <div class="grid grid-cols-4 gap-2">
        {% for item in items %}
            <div>
                <a href="{% url 'item:detail' item.id %}">
                    <div>
                        <img src="{{ item.image.url }}" class="rounded-t-xl aspect-square bg-white" >
                    </div>
                    <div class="p-6 bg-orange-600 rounded-b-xl">
                        <h2 class="text-2xl text-white">{{ item.name }}</h2>
                        <p class="text-black font-semibold">Price: {{ item.price }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
<div class="mt-6 px-6 py-6 bg-amber-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center font-bold text-orange-600">Categories</h2>
    <div class="grid grid-cols-4 gap-3">
        {% for category in categories %}
            <div>
                <a href="#">
                    <div class="p-6 bg-orange-600 rounded-xl">
                        <h2 class="text-2xl text-white font-semibold">{{ category.name }}</h2>
                        <p class="text-black font-semibold text-black">{{ category.items.count }} items</p>
                    </div>
                </a>
            </div>

        {% endfor %}
    </div>
</div>

  {% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}
{% block title %}Login{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
  <h1 class="mb-6 p-4 text-3xl bg-black rounded-xl text-white">Login</h1>
  <form method="post" action=".">
    {% csrf_token %}
    <div class="mb-3">
      <label class="inline-block mb-2 text-orange-600 font-bold">Username</label><br>
      {{ form.username }}
    </div>
    <div class="mb-3">
      <label class="inline-block mb-2 text-orange-600 font-bold">Password</label><br>
      {{ form.password }}
    </div>
    {% if form.errors or form.non_field_errors %}
    <div class="mb-3 p-6 bg-red-100 rounded-xl">
      {% for field in form %}
      {{ field.errors}}
      {{ form.non_field_errors }}
      {% endfor %}
    </div>
    {% endif %}
    <div class="mt-4 flex justify-end">
    <button class="py-2 px-4 text-lg bg-lime-800 hover:bg-lime-200 hover:text-black rounded-xl text-white">Submit</button>
    </div>
  </form>
</div>

{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}
{% block title %}SignUp{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
  <h1 class="mb-6 p-4 text-3xl bg-black rounded-xl text-white">Sign UP</h1>
  <form method="post" action=".">
    {% csrf_token %}
    <div class="mb-3">
      <label class="inline-block mb-2 text-orange-600 font-bold">Username</label><br>
      {{ form.username }}
    </div>
    <div class="mb-3">
      <label class="inline-block mb-2 text-orange-600 font-bold">Email</label><br>
      {{ form.email }}
    </div>
    <div class="mb-3">
      <label class="inline-block mb-2 text-orange-600 font-bold">Password</label><br>
      {{ form.password1 }}
    </div>
    <div class="mb-3">
      <label class="inline-block mb-2 text-orange-600 font-bold">Confirm Password</label><br>
      {{ form.password2 }}
    </div>
    {% if form.errors or form.non_field_errors %}
    <div class="mb-3 p-6 bg-red-100 rounded-xl">
      {% for field in form %}
      {{ field.errors}}
      {{ form.non_field_errors }}
      {% endfor %}
    </div>
    {% endif %}
    <div class="mt-4 flex justify-end">
    <button class="py-2 px-4 text-lg bg-lime-800 hover:bg-lime-200 hover:text-black rounded-xl text-white">Create Account</button>
    </div>
  </form>
</div>

{% endblock %}